# Lab: One-Hot Encoding, Bag of Words, and TF-IDF
**Name:** Ankit Ahirrao
**Roll No:** 2025PCS0021
**Course:** NLP
**Date:** 22 Jan 2026


## 1. Objective
*   Understand how text and categorical data can be converted into numerical features.

*   Apply basic text representation techniques such as One-Hot Encoding, Bag of Words, and TF-IDF.

*   Identify and explain problems related to high dimensionality and sparse data.

*   Measure similarity between documents using vector representations.

*   Compare different text vectorization methods and understand their advantages and limitations.

## 2. Dataset Description
### 2.1 Toy Dataset
The toy dataset is defined as follows:

D1: machine learning is fun

D2: machine learning is powerful

D3: deep learning is fun

D4: deep learning powers modern ai



### 2.2 Real-World Dataset

I selected product review real world dataset. The Amazon Product Reviews dataset is used as a real-world textual dataset.
It contains customer-written reviews expressing opinions about products.

A small subset of 300 reviews is selected to demonstrate preprocessing,
text vectorization techniques, and similarity analysis on real-world data.

## First Part - Toy Dataset

### Toy Dataset
The following toy dataset is used for demonstrating text preprocessing and vectorization techniques.



In [ ]:
corpus = [
    "machine learning is fun",
    "machine learning is powerful",
    "deep learning is fun",
    "deep learning powers modern ai"
]

## 3. Preprocessing

The following preprocessing steps are applied to the text data:
- Convert all text to lowercase
- Remove punctuation
- Tokenize the text into words
- Remove stopwords (optional)



In [ ]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def preprocess_text(text):
    text = text.lower() #Lowercasing
    tokens = re.findall(r'\b[a-z]+\b', text) # Regex-based tokenisation
    words = [word for word in tokens if word not in ENGLISH_STOP_WORDS] # stopword removal
    return ' '.join(words)

preprocessed_corpus = [preprocess_text(doc) for doc in corpus]
preprocessed_corpus

['machine learning fun',
 'machine learning powerful',
 'deep learning fun',
 'deep learning powers modern ai']

## 4. One-Hot Encoding

One-hot encoding represents each word as a binary vector indicating its presence or absence in a document.


## 4. One-Hot Encoding


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
X_onehot = vectorizer.fit_transform(preprocessed_corpus)

print("Vocubulary:", vectorizer.get_feature_names_out())
print("One-Hot Encoded Matrix:")
print(X_onehot.toarray())


Vocubulary: ['ai' 'deep' 'fun' 'learning' 'machine' 'modern' 'powerful' 'powers']
One-Hot Encoded Matrix:
[[0 0 1 1 1 0 0 0]
 [0 0 0 1 1 0 1 0]
 [0 1 1 1 0 0 0 0]
 [1 1 0 1 0 1 0 1]]


## 5. Bag of Words (BoW)

Bag of Words represents text by counting the frequency of each word in a document.


In [ ]:
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(preprocessed_corpus)

print("Vocubulary:", vectorizer.get_feature_names_out())
print("Bag of Words Matrix:")
print(X_bow.toarray())


Vocubulary: ['ai' 'deep' 'fun' 'learning' 'machine' 'modern' 'powerful' 'powers']
Bag of Words Matrix:
[[0 0 1 1 1 0 0 0]
 [0 0 0 1 1 0 1 0]
 [0 1 1 1 0 0 0 0]
 [1 1 0 1 0 1 0 1]]


## 6. TF-IDF

TF-IDF assigns higher weight to important words and reduces the weight of common words.


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(preprocessed_corpus)

print("Vocubulary:", vectorizer.get_feature_names_out())
print("TF-IDF Matrix:")
print(X_tfidf.toarray())


Vocubulary: ['ai' 'deep' 'fun' 'learning' 'machine' 'modern' 'powerful' 'powers']
TF-IDF Matrix:
[[0.         0.         0.64043405 0.42389674 0.64043405 0.
  0.         0.        ]
 [0.         0.         0.         0.37919167 0.5728925  0.
  0.72664149 0.        ]
 [0.         0.64043405 0.64043405 0.42389674 0.         0.
  0.         0.        ]
 [0.50676543 0.39953968 0.         0.26445122 0.         0.50676543
  0.         0.50676543]]


## 7. Similarity Analysis

Cosine similarity is used to measure similarity between documents.


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(X_tfidf)
similarity_matrix


array([[1.        , 0.52763798, 0.58984422, 0.11210001],
       [0.52763798, 1.        , 0.16073811, 0.1002777 ],
       [0.58984422, 0.16073811, 1.        , 0.36797883],
       [0.11210001, 0.1002777 , 0.36797883, 1.        ]])

In [ ]:
## Finding most similar document pair

import numpy as np
np.fill_diagonal(similarity_matrix, 0)
max_similarity = np.unravel_index(similarity_matrix.argmax(), similarity_matrix.shape)
print("Most similar documents indexes:", max_similarity)

## Mapping index to actual document text
print("Document 1:", preprocessed_corpus[max_similarity[0]])
print("Document 2:", preprocessed_corpus[max_similarity[1]])

Most similar documents indexes: (np.int64(0), np.int64(2))
Document 1: machine learning fun
Document 2: deep learning fun


## 8. Comparative Study
| Feature | One-Hot Encoding | Bag of Words (BoW) | TF-IDF |
|-------|------------------|-------------------|--------|
| Representation | Binary (0 or 1) | Frequency-based | Weighted (TF × IDF) |
| Word Order | Ignored | Ignored | Ignored |
| Vocabulary Size | Large | Large | Large |
| Sparsity | Very High | Very High | Very High |
| Captures Frequency | No | Yes | Yes |
| Captures Importance | No | No | Yes |
| Effect of Common Words | Same as rare words | Dominates counts | Down-weighted |
| Use Case | Simple presence check | Basic text analysis | Information retrieval, similarity |




## 9. Observations

1. Text preprocessing such as lowercasing, punctuation removal, tokenization, and stopword removal significantly reduces noise in the dataset and improves the quality of feature extraction.

2. One-Hot Encoding represents words using binary values, indicating only the presence or absence of terms. This results in highly sparse vectors and does not capture word frequency.

3. Bag of Words (BoW) captures the frequency of words in documents, providing more information than One-Hot Encoding. However, it does not consider the importance of words across documents.

4. TF-IDF assigns higher weights to important and less frequent words while reducing the impact of commonly occurring words. This leads to better feature representation.

5. All vectorization techniques produce sparse matrices due to the large vocabulary size compared to the number of words in each document.

6. Cosine similarity effectively measures the similarity between documents by comparing their vector representations.

7. TF-IDF-based similarity analysis produces more meaningful similarity results compared to One-Hot Encoding and BoW, as it emphasizes informative words.

8. Documents containing similar keywords such as “learning” and “fun” show higher similarity scores.


## 10. Conclusion

In this experiment, different text vectorization techniques such as One-Hot Encoding, Bag of Words, and TF-IDF were implemented and analyzed using a toy dataset. Text preprocessing steps helped in cleaning the data and improving feature representation.

It was observed that One-Hot Encoding only captures the presence of words, while Bag of Words considers word frequency but ignores term importance. TF-IDF proved to be more effective as it assigns higher weights to important words and reduces the influence of commonly occurring terms.

Cosine similarity was used to measure document similarity, and TF-IDF-based similarity analysis produced more meaningful and accurate results. Overall, TF-IDF is more suitable for text representation and similarity analysis in practical natural language processing applications.


## Second Part - Real World Dataset (Amazon Product Reviews)

### 1. Dataset Description

The Amazon Product Reviews dataset is used as a real-world textual dataset.
It contains customer-written reviews expressing opinions about products.

A small subset of 300 reviews is selected to demonstrate preprocessing,
text vectorization techniques, and similarity analysis on real-world data.

### 2. Load Dataset

In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/Reviews.csv",
                 engine="python",
                 on_bad_lines="skip",
                 quoting=3)

df = df[['Text']].dropna()

df = df.sample(300, random_state=42)

corpus = df['Text'].tolist()

print("Number of reviews loaded:", len(corpus))

Number of reviews loaded: 300


In [ ]:
corpus[:3]

["I thought the whole figs would be softer for spreading but they are not. You have figs laying in a very sweet syrup. I've only tried it on toast one time and it was way to sweet to eat. The figs just lay on top unspreadable. I would not buy again. Save your money.",
 'My cat could not wait to eat some of this food.  She really seemed to enjoy the food.  She ate it up very quickly.  In my opinion any cat would love to get some of this food.',
 'My two Chihuahuas absolutely love these treats. They get one at bedtime and follow me around until I give it to them. These are great healthy moist treats for a good price. Would highly recommend.']

### 3. Preprocessing

The following preprocessing steps are applied to the text data:

- Convert all text to lowercase to ensure uniformity.
- Perform regex-based tokenization to extract valid word tokens.
- Remove special characters and punctuation during tokenization.
- Remove common English stopwords to reduce noise and improve feature quality.


In [ ]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def preprocess(text):
  text  = text.lower()
  tokens = re.findall(r'\b[a-z]+\b', text) #regex tokenization
  tokens = [w for w in tokens if w not in ENGLISH_STOP_WORDS] #stop word removal
  return " ".join(tokens)

preprocessed_corpus = [preprocess(doc) for doc in corpus]
preprocessed_corpus[:3]

['thought figs softer spreading figs laying sweet syrup ve tried toast time way sweet eat figs just lay unspreadable buy save money',
 'cat wait eat food really enjoy food ate quickly opinion cat love food',
 'chihuahuas absolutely love treats bedtime follow great healthy moist treats good price highly recommend']

###4. One-Hot Encoding
One-hot encoding represents each word as a binary vector indicating the presence or absence of a word in a document.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

onehot_vectorizer = CountVectorizer(binary=True, max_features=5000)
X_onehot = onehot_vectorizer.fit_transform(preprocessed_corpus)

print("Vocabulary:", onehot_vectorizer.get_feature_names_out())
print("One-Hot Shape:", X_onehot.shape)

Vocabulary: ['ability' 'able' 'absolutely' ... 'zero' 'zin' 'ziploc']
One-Hot Shape: (300, 1787)


### 5. Bag of Words (BoW)

Bag of Words represents documents using the frequency of each word.


In [ ]:
bow_vectorizer = CountVectorizer(max_features=5000)
X_bow = bow_vectorizer.fit_transform(preprocessed_corpus)

print("BoW Shape:", X_bow.shape)

BoW Shape: (300, 1787)


### 6. TF-IDF

TF-IDF assigns higher weights to important words and reduces the impact of commonly occurring words.


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_tfidf = tfidf_vectorizer.fit_transform(preprocessed_corpus)

print("TF-IDF Shape:", X_tfidf.shape)

TF-IDF Shape: (300, 1787)


### 7. Similarity Analysis

Cosine similarity is used to measure similarity between documents.


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

similarity_matrix = cosine_similarity(X_tfidf)

#Remove self-similarity
np.fill_diagonal(similarity_matrix, 0)

#Find most similar document pair
max_similarity = np.unravel_index(similarity_matrix.argmax(), similarity_matrix.shape)
print("Most similar documents indexes:", max_similarity)

Most similar documents indexes: (np.int64(23), np.int64(125))


In [ ]:
i, j = max_similarity
print("Document 1:", corpus[i])
print("Document 2:", corpus[j])

Document 1: $136 for 12 boxes?<br /><br />Is this a rare item?<br /><br />That's $11.33 a box.<br /><br />I think the item might be a bit overpriced.
Document 2: it's my favorite snack. Amazon has the best price ever for this.<br /><br />cheaper than korean grocery website and korean market.<br /><br />I'm gonna order again


### 8. Comparative Study

| Technique | Representation | Observation |
|---------|----------------|-------------|
| One-Hot Encoding | Binary | Very sparse and high dimensional |
| Bag of Words | Frequency-based | Common words dominate |
| TF-IDF | Weighted | Best for similarity analysis |


### 9. Observations

1. Real-world text data contains noise and requires preprocessing.
2. Vocabulary size increases significantly, leading to sparse vectors.
3. One-Hot Encoding is inefficient for large datasets.
4. Bag of Words captures frequency but ignores importance.
5. TF-IDF provides better feature weighting.
6. Cosine similarity effectively identifies similar reviews.


### 10. Conclusion

In this experiment, One-Hot Encoding, Bag of Words, and TF-IDF were applied to a real-world Amazon product reviews dataset.
Preprocessing improved the quality of text representation.

TF-IDF proved to be the most effective technique, as it considers both term frequency and term importance.
Cosine similarity combined with TF-IDF produced meaningful document similarity results, making TF-IDF suitable for real-world NLP applications.
